export const EVENT_TRACKING_CATEGORY = {
  LIST: "LIST",
  SIGNUP: "SIGNUP",
  SHARING: "SHARING",
  SOCIAL_MEDIA_LOGIN: "SOCIAL_MEDIA_LOGIN",
};

export const EVENT_TRACKING_LABEL = {
  LIST_CREATED: "LIST_CREATED",
  PRODUCT_ADDED: "PRODUCT_ADDED",
  SIGNUP: "SIGNUP",
  SHARE_LIST: "SHARE_LIST",
  SOCIAL_MEDIA_LOGIN: "SOCIAL_MEDIA_LOGIN",
};
